"""
Distance estimation model parameters for hook operation.
This file is automatically generated by distance_models.py.
Manual changes to this file may be overwritten.
"""

# Best model according to AIC: Polynomial Degree 2
# AIC: 42.25, R²: 0.9918, RMSE: 3.65 cm

# -- Linear model constant --
DISTANCE_CALIBRATION_CONST = 2150.0  # cm*px (linear model k)

# -- Exponential model parameters --
DISTANCE_EXP_A = 764.061183  # Amplitude
DISTANCE_EXP_B = 0.108721  # Decay rate
DISTANCE_EXP_C = 24.791544  # Offset

# -- Polynomial model coefficients --
# Format: [a4, a3, a2, b, c] for a4x^4 + a3x^3 + a2x^2 + bx + c
DISTANCE_POLY_COEFFS = [
    6.851615656486516e-05,
    -0.008880076049142692,
    0.7963046331872384,
    -33.309592345506495,
    520.2857939249507,
]

# -- Logarithmic model parameters --
DISTANCE_LOG_A = -173.667171  # Coefficient
DISTANCE_LOG_B = 637.480102  # Offset

# -- Inverse Power model parameters --
DISTANCE_K = 10000.0000  # Coefficient
DISTANCE_P = 1.5004  # Power

# -- Robust Polynomial Degree 2 model parameters --
DISTANCE_ROBUST_A = 0.393453  # x² coefficient
DISTANCE_ROBUST_B = -25.630841  # x coefficient  
DISTANCE_ROBUST_C = 234.170359  # constant term

# -- Target parameters --
TARGET_DISTANCE_CM = 60.      # Target distance from hose in cm
DISTANCE_TOLERANCE_CM = 3.    # Tolerance for distance estimation