name: Build and Test (Kilted)

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"

jobs:
  build_and_verify:
    name: ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: amd64, runner: ubuntu-24.04 }
          - { arch: arm64, runner: ubuntu-24.04-arm }
    uses: ./.github/workflows/_build-verify.yml
    with:
      ros_distro: kilted
      install_drone: all
      runner: ${{ matrix.runner }}
