name: Build and Test (Jazzy)

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"

jobs:
  build_and_verify:
    uses: ./.github/workflows/_build-verify.yml
    with:
      ros_distro: jazzy
